### ISSUE TITLE
error in implementation of Inceptionv1Module?

### ISSUE THREAD

**Issue by fotto** [krishnonwork/mathematical-methods-in-deep-learning-ipython#33]
File: `python/ch11/11.3.2-inception.ipynb`
Class `Inceptionv1Module`

According to the book (section 11.2.2 and figure 11.8, respectively) in the "dimensionality reduced" inception block the 3rd branch contains a 1x1 conv followed by  5x5 conv.

Hence in the code the definition of `self.branch5x5_1` should start with `kernal_size=1` (and no padding). 
Compare with definition of `self.branch3x3_1`

**Comment by ananya-h-a** [comment]
That's a good catch. 

This has been fixed by #34 . Thanks!
